server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive


    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

